### ISSUE TITLE
Stereochemistry 

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/fragmenter#5]
How should we handle stereochemistry? 

The phase angle in the Fourier series is restricted to 0 or 180. This allows the same torsion types to be used for enantiomers. If that's the case, do we need to consider enantiomers different molecules? 

For the time being I'll add both the canonical isomeric SMILES and a canonical SMILES to the JSON specs for fragments.

**Comment by jchodera** [comment]
I presume we currently want to use the canonical isomeric SMILES string as our way of judging whether fragments are unique. Later on, we may relax that.

**Comment by ChayaSt** [comment]
For the incoming molecules to fragment - should we enforce isomeric SMILES? If it's not isomeric, should we generate an isomeric SMILES before we generate conformations of the molecule to fragment? 
In general I need to add a cleanup step for incoming molecules - generating an isomeric SMILES can be part of that step. However, shouldn't we also enumerate enantiomers if several stereocenters exist? The fragments can be different  for different enantiomers.

**Comment by jchodera** [comment]
To clarify here:
* For incoming molecules, we need one stage that expands ambiguous stereochemistry and enumerates likely protonation/tautomeric states. At this point, all molecules will then have specific stereochemistry and explicit hydrogens.
* We should expand the JSON generated to specify *both* explicit-hydrogen canonical isomeric SMILES and non-isomeric SMILES so that either can be used as a key for indexing.
* The resulting molecules can then be distributed in parallel to another function, which fragments each of these molecules and passes fragments on to the next stage.

**Comment by jchodera** [comment]
I think all five will be useful! But it's possible 3 and 5 are redundant if the tautomeric and charge state are both encoded by 2 and 4. This is probably a question for @bannanc or @cbayly13

**Comment by ChayaSt** [comment]
Stereochemistry enumeration was addressed with https://github.com/openforcefield/fragmenter/pull/10.
