### ISSUE TITLE
Functional groups on rings do not come along with ring

### ISSUE THREAD

**Issue by ChayaSt** [openforcefield/fragmenter#51]
When functional groups are tagged and they are also partially part of a ring (amide where the N is in a ring), the rest of the functional group does not come along with the ring. It should.

**Comment by SimonBoothroyd** [comment]
I think this is fixed in the latest version of the code (see [here](https://github.com/openforcefield/fragmenter/blob/0534a00da3b23ce3ba637e23091fef990ad5daa2/fragmenter/fragment.py#L1005-L1011)). I'll close this for now but this should be re-opened if any examples of this pop-up when using the latest versions.
