### ISSUE TITLE
Omega returned error code 0

### ISSUE THREAD

**Issue by ewu20** [openforcefield/fragmenter#66]
Hi, 

I am trying to fragment a molecule. I have a simple script that has worked for the other molecules that I've fragmented but when I try to run this molecule (C[CH]1CN=C(N1)C2=CC=C(NC(=O)NC3=CC=C(C=C3)C(=O)NC4=CC=C(C=C4)C5=N[CH](C)CN5)C=C2) it gives me the following error: 
____________________________________________________________________________________________________________________________________
runfile('/Users/emmawu/Downloads/fragment_molecules.py', wdir='/Users/emmawu/Downloads')
Warning: \~{N}-[4-(4-methyl-4,5-dihydro-1~\{H}-imidazol-2-yl)phenyl]-4-[[4-(5-methyl-4,5-dihydro-1~{H}-imidazol-2-yl)phenyl]carbamoylamino]benzamide: Failed due to unspecified stereochemistry
Traceback (most recent call last):

  File "/Users/emmawu/Downloads/fragment_molecules.py", line 17, in <module>
    file.fragment()

  File "/Users/emmawu/anaconda3/lib/python3.6/site-packages/fragmenter/fragment.py", line 873, in fragment
    self.calculate_wbo()

  File "/Users/emmawu/anaconda3/lib/python3.6/site-packages/fragmenter/fragment.py", line 900, in calculate_wbo
    self.molecule = get_charges(self.molecule)

  File "/Users/emmawu/anaconda3/lib/python3.6/site-packages/fragmenter/chemi.py", line 75, in get_charges
    charged_copy = generate_conformers(molecule, max_confs=max_confs, strict_stereo=strict_stereo, **kwargs)  # Generate up to max_confs conformers

  File "/Users/emmawu/anaconda3/lib/python3.6/site-packages/fragmenter/chemi.py", line 171, in generate_conformers
    raise(RuntimeError("omega returned error code %d" % status))

RuntimeError: omega returned error code 0
____________________________________________________________________________________________________________________________________

Here is the code: 
`m = chemi.smiles_to_oemol('C[CH]1CN=C(N1)C2=CC=C(NC(=O)NC3=CC=C(C=C3)C(=O)NC4=CC=C(C=C4)C5=N[CH](C)CN5)C=C2')` 
`file = fragment.WBOFragmenter(m)` 
`file.fragment()` 
`name = '67735'`
`file.depict_fragments(fname="{}.pdf".format(name))`
`with open ('{}.json'.format(name), 'w') as f:`
`    json.dump(file.to_json(), f , indent=2, sort_keys=True)`

`with open ('{}.json'.format(name), 'r') as f:`
`    data = list(dict(json.load(f)).keys())`

`with open ('{}.smi'.format(name), 'w') as f:`
`    f.writelines([x + "\n" for x in data])`

As always, thank you so much for any help and input! 

Best, 
Emma

**Comment by SimonBoothroyd** [comment]
I realise that this issue is quite old (apologies that no one has responded sooner), but for posterity:

Currently it is required that the full stereochemistry of a molecule must be specified in order to fragment it. This is due to us using conformer based methods to compute the Wiberg bond orders, which themselves require full information about the stereochemistry.

For the above molecule the 5 membered ring carbons that the methyl groups are attached to on either end of the molecule are chiral but the SMILES pattern does not state whether they or (R) or (S). This can be fixed be providing the stereochemistry if none, or selecting a random stereoisomer which, I don't think at least, should alter the fragmentation here:

```
"C[C@H]1CNC(=N1)c2ccc(cc2)NC(=O)c3ccc(cc3)NC(=O)Nc4ccc(cc4)C5=NC[C@@H](N5)C"
```
